### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by shweta037** [iexbase/tron-api#1]
Looks too easy but api not working.....

**Comment by serderovsh** [comment]
Check the default node: http://13.125.210.234:8090

$fullNode = new HttpProvider('http://13.125.210.234:8090');

**Comment by serderovsh** [comment]
The last release was 7 days ago.
Update the package to v1.3.2

```bash
> composer.phar update iexbase/tron-api
```

**Comment by shweta037** [comment]
Thanks for your reply @serderovsh do you have working example for node js as well for tron coin.I was even trying to work with tronix.js but not able createTransaction and send transaction.Getting this...
The deserializeTransaction is  : 147,246,,,184,59,183,243,185,12,202,84,,,,1537516374000,,,1,type.googleapis.com/protocol.TransferContract,10,21,65,157,171,82,157,66,169,49,246,215,142,180,5,69,122,0,182,91,217,49,11,18,21,65,186,138,235,140,169,49,133,133,183,210,87,106,117,203,8,214,38,37,212,117,24,160,141,6,170,73,82,110,241,56,195,78,119,204,241,30,228,5,103,221,15,18,88,172,73,226,157,17,32,198,209,155,44,186,122,134,92,16,58,175,176,75,95,39,16,49,213,19,223,145,205,89,93,89,215,140,38,187,154,127,81,116,155,5,195,128,38,4,1,,,
this is transaction id[object Object]
My function is this ..
async function run() {
    // Create and broadcast transaction
    const transaction = await client.createTransaction(
        '1e29bcdc573ec404b25ea5ec9f66b2f6f39c596f350dca5dfadb9f43099f578d',
        'TUiAwy29KbwqbmjccHSyWHa5fUFiW8o5Xn',
        'TZG7vRbLKMLV9cpKh4McsYtrWVdZ8kQAp2',
        1,
    );
    console.log("this is transaction id isssssssssssssss :" +transaction); // result
}

run();

What wrong i am doing not getting .

This looks totally different from other coins...

**Comment by serderovsh** [comment]
```php
$fullNode = new HttpProvider('http://13.125.210.234:8090');

$tron = new \IEXBase\TronAPI\Tron($fullNode);
$tron->setAddress('authTronAddress');
$tron->setPrivateKey('privateKey');

try {
    $transfer = $tron->sendTransaction('authTronAddress', 'ToAddress', 1);
} catch (\IEXBase\TronAPI\Exceptions\TronException $e) {
    die($e->getMessage());
}

var_dump($transfer); // success result

**Tested 2 minutes ago**

**Comment by shweta037** [comment]
getting this error...
Notice: Undefined index: signature in /opt/lampp/htdocs/tron/tron-api/vendor/iexbase/tron-api/src/Tron.php on line 479

**Comment by serderovsh** [comment]
It seems to me that you are specifying a private key incorrectly

```php
$tron->generateAddress();
```
Generate a new address, and try through it.
