### ISSUE TITLE
How to get balance (TRC10 - TRC20)

### ISSUE THREAD

**Issue by kaankozan** [iexbase/tron-api#10]
How to het all token balance??

![screenshot_2018-11-30-23-14-44](https://user-images.githubusercontent.com/38933295/49312671-e1f69a80-f4f5-11e8-9b49-b865d6423d42.png)

**Comment by serderovsh** [comment]
```php
$tron->getAccount('address')
```

**Comment by kaankozan** [comment]
Thank u so much

**Comment by kaankozan** [comment]
$tron->getAccount('address')

This code wonderfull working but maybe time i have a problem whats wrong how to fixed

![img_20181226_123647](https://user-images.githubusercontent.com/38933295/50441404-92946600-090b-11e9-8b99-f05ce10c60f8.png)

**Comment by serderovsh** [comment]
Possibly connected with the connection to the node.

**Comment by serderovsh** [comment]
Noda does not respond

**Comment by kaankozan** [comment]
hi 
i use 
$tron->getAccount('address')

but i dont get trc20 token balance 

how to find trc20 token balance
