### ISSUE TITLE
TRC20Contract class has no method to change feeLimit

### ISSUE THREAD

**Issue by maxbasmanov** [iexbase/tron-api#123]
In TRC20Contract class there is no method to set fee limit other than
private int $feeLimit = 10;

Need to add setFeeLimit($newFeeLimit) method:

public function setFeeLimit($newFeeLimit)
{
    $this->feeLimit = $newFeeLimit;

    return $this->feeLimit;
}

The problem:
Whet transfering TRX amount less than $feeLimit to the wallet (example: 5 TRX) to get USDT tokens from that wallet the following error occures.
FAILED-OUT OF ENERGY
5 TRX are burned from the wallet: Burn TRX to get resources 5 TRX
But transaction fails.

Result:
0 TRX on the wallet and USDT tokest not taken from the wallet.

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/commit/d45551bee737eb5bcf3b643a8a3b8e021c4f5163
