### ISSUE TITLE
CONTRACT_VALIDATE_ERROR

### ISSUE THREAD

**Issue by vsalgueiro7** [iexbase/tron-api#124]
I'm trying the following problem, when trying to transfer 

help me 

![image](https://user-images.githubusercontent.com/92699116/161177644-263052e7-46c6-421a-8798-85107b87ce99.png)

![image](https://user-images.githubusercontent.com/92699116/161177694-5f0a3b25-5f5a-40da-ae71-ffe443480f3b.png)

**Comment by Hateem76** [comment]
@vsalgueiro7 hey,, did you solve your "CONTRACT_VALIDATE_ERROR" ?
