### ISSUE TITLE
is it secure to set private key and send transaction?

### ISSUE THREAD

**Issue by zottirik** [iexbase/tron-api#15]
is it secure to set $tron->setPrivateKey and $tron->sendTrx?

is Private key sending to https://api.trongrid.io?

Thanks,

**Comment by serderovsh** [comment]
api.trongrid.io - is the safest node.
For TRON api from PHP we haven't done offline signing yet.

**Comment by gituser** [comment]
No, it's not secure to send your private key to the 3rd party node over the internet.

There should be offline signing implemented.
