### ISSUE TITLE
PHP version required

### ISSUE THREAD

**Issue by aralsoft** [iexbase/tron-api#2]
I get the following error when i try to install with composer,

./composer.phar require iexbase/tron-api
                                                                                                    
  [InvalidArgumentException]                                                                              
  Package iexbase/tron-api at version  has a PHP requirement incompatible with your PHP version (7.0.31)  

What version of PHP is needed ?

**Comment by serderovsh** [comment]
PHP 7.1 >

**Comment by serderovsh** [comment]
no, we try to follow the standard "TronWeb", almost all the features of "TronWeb" are in the plugin "TronAPI"

**Comment by aralsoft** [comment]
Thanks. I moved my site to a fresh server with php7.2 so will try to install it again now.

**Comment by aralsoft** [comment]
Got it working. Superb. Thanks for this.
