### ISSUE TITLE
how to get balance trc20

### ISSUE THREAD

**Issue by kaankozan** [iexbase/tron-api#20]
hi
i use
$tron->getAccount('address')

but i dont get trc20 token balance

how to find trc20 token balance

**Comment by kaankozan** [comment]
can u help me

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/blob/master/src/Tron.php#L464

**Comment by kaankozan** [comment]
but this method doesnt get trc20 token balance...

**Comment by kaankozan** [comment]
can u help me pls

**Comment by serderovsh** [comment]
there is no other method in the Tron documentation

Only available https://github.com/iexbase/tron-api/blob/master/src/Tron.php#L464

**Comment by kaankozan** [comment]
>function balanceOf(address tokenOwner) public constant returns (uint balance);

https://developers.tron.network/docs/trc10-token

**Comment by serderovsh** [comment]
This is a contact balance, in tron-api there is no possibility to manage a contract yet.

**Comment by kaankozan** [comment]
do u add to contact balance

**Comment by mr-mr7** [comment]
solved it???????
