### ISSUE TITLE
Implement similar method to `isAddress` like in tron web library

### ISSUE THREAD

**Issue by vladyslavstartsev** [iexbase/tron-api#23]
https://github.com/tronprotocol/tron-web/blob/8b8dab06306efdee5dc534584c2acfff278b4ab1/src/index.js#L335

it will be nice to have similar method on this library

**Comment by serderovsh** [comment]
In the near future we will add

**Comment by gfijrb** [comment]
No thanks))
[https://gist.github.com/gfijrb/f7528298878061e02f2c7ac308a16dc8](https://gist.github.com/gfijrb/f7528298878061e02f2c7ac308a16dc8)

**Comment by gfijrb** [comment]
but really I dont know how strongly chack is hash of address right, so ..(

**Comment by serderovsh** [comment]
added
