### ISSUE TITLE
fromtron() problem

### ISSUE THREAD

**Issue by kaankozan** [iexbase/tron-api#24]
code
echo fromtron(10);
>>>1.0E5

how to fix it

**Comment by serderovsh** [comment]
It's not a problem

See examples:
https://github.com/iexbase/tron-api/blob/master/examples/amount.php

**Comment by kaankozan** [comment]
do you test it ?

i dont have any problem this line for 123sun
echo fromtron(123);
>0.000123

but i have a problem 12sun
echo fromtron(12);
>1.2E-5

**Comment by serderovsh** [comment]
```php
echo $tron->toSun(12);
```

**Comment by kaankozan** [comment]
my balance 0.000012 trx but

getaccount in balance return 12 

i need a getaccount in balance 12 to convert 0.000012 trx but response fromtron 1.2E-5 
@serderovsh

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/blob/a8ffbadae8b4482542dec282f08283c6a08db1d1/src/Tron.php#L490

I have this plugin connected with exchange points. Everything works well
