### ISSUE TITLE
Sending transactions

### ISSUE THREAD

**Issue by aralsoft** [iexbase/tron-api#3]
var_dump($tron->sendTransaction('from', 'to', 'amount'));

Are the from and to addresses decoded from base58 format ? ie. do they start with the 'T' as seen in wallets or '41' as seen in blockchain transaction data ?

how many decimal places has the amount got ? ie. to send 1 tron what do u need to enter ? as opposed to say 1.01 tron ?

Thanks.

**Comment by aralsoft** [comment]
Thx

**Comment by aralsoft** [comment]
Sorry to be a pain but in your example shouldn't the $tron->send method be $tron->sendTransaction ? I could not find a send method.

Also what does the set address do ? is that the from address ? and is this required ? I assume the private key is the pk of the from address. As your example uses the same address for both from and to addresses i am a bit confused.

**Comment by serderovsh** [comment]
```php
$tron->send(); // Copy sentTransaction()
```

All [https://github.com/iexbase/tron-api/tree/master/examples](examples)

**Comment by aralsoft** [comment]
Great what about the setAddress method ? is that the from address ?

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/blob/master/src/Tron.php#L628

**Comment by aralsoft** [comment]
Great. working perfectly. Thanks again.
