### ISSUE TITLE
getBalance method gives wrong amount

### ISSUE THREAD

**Issue by vladyslavstartsev** [iexbase/tron-api#30]
`$tron->getBalance('TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9')` 
or even 
`$tron->getBalance('TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9',true) `

I get wrong balance, because in first case I get 15286180772100810 and in second case I get `15286180772.101`
the difference is rounding done after `.10` 
this method should return `15286180772.10081`
I know that `0.001` is not that much but I still makes wrong calculations.
I would like to see correct result up to 18 decimals (that's what trc-20 max decimals are)

Is there a way to do this?

**Comment by serderovsh** [comment]
```php
$price = (float)$q->getBalance('TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9');
echo $price / 1e6;
```

**Comment by vladyslavstartsev** [comment]
> ```
> / 1e6
> ```

the value is still `15286180772.101`

we need `15286180772.10081`

**Comment by serderovsh** [comment]
```php
number_format((float)$price / 1e6, 5,'.','')
```

**Comment by serderovsh** [comment]
```php
echo sprintf('%0.5f', (floatval($price / 1e6)));
```
