### ISSUE TITLE
Transaction builder TRC20

### ISSUE THREAD

**Issue by CryTrExcom** [iexbase/tron-api#33]
Any way to transfer contract TRC20 to one account to another?
Tronweb have this function, is possible to add it?
We see trigger smart contract but we need just transfer contract.

Thanks

**Comment by serderovsh** [comment]
Currently there is no functionality for working with contracts.

**Comment by CryTrExcom** [comment]
impossible to transfer trc20 from one address to another?

**Comment by kaankozan** [comment]
imposible is not 

if using true contract address with (transferFrom) inpust in abi 

u did it triggeramartcontract
