### ISSUE TITLE
Public address from private key and...

### ISSUE THREAD

**Issue by CryTrExcom** [iexbase/tron-api#34]
Is possible to set public address using private key? And or have private key and publick address from tronlink?

**Comment by serderovsh** [comment]
Tron-API for php has not yet implemented this functionality.
for python there is

**Comment by CryTrExcom** [comment]
Can add it soon?

**Comment by serderovsh** [comment]
We now have other priority projects. Add this functionality in the near future.

**Comment by srdante** [comment]
Any update?

**Comment by serderovsh** [comment]
There is no version for "PHP"

**Comment by atlaschiew** [comment]
hi i have made up an article about this issue, kindly refer to https://www.btcschools.net/tron/tron_address.php . however, an address is not activated, you need refer to other article to activate it :)

Atlas Chiew
btcschools.net
