### ISSUE TITLE
triggerSmartContract return OTHER_ERROR 

### ISSUE THREAD

**Issue by gfijrb** [iexbase/tron-api#37]
Contract source code: https://github.com/gfijrb/tronditeco/blob/master/contracts/Test.sol 

Curl example 
```
// request 
curl -G https://api.shasta.trongrid.io/wallet/triggersmartcontract -X POST -d '{"contract_address":"TWMfdPPmzSybGfT47F3c9hqdMch6vVFXVG","function_selector":"doit()","parameter":"","fee_limit":1000000,"call_value":0,"owner_address":"TRC6hn9q7xdKZ67E3VyRpADo6EAeFjyEyu"}'

// response
{"result":{"code":"OTHER_ERROR","message":"636c617373206f72672e74726f6e2e636f72652e73657276696365732e687474702e4a736f6e466f726d6174245061727365457863657074696f6e203a20313a313a20457870656374656420227b222e"}}
```

And can you explain. In code if func by signature has params they must be sent as usual string or in bytecode?

contract_address - HEX or BASE58
owner_address - HEX or BASE58
fee_limit - max possible value?

OTHER_ERROR : msg: blablabla....
How to read this message?

**Comment by kaankozan** [comment]
$message = isset($result['result']['message']) ?
            $this->tron->hexString2Utf8($result['result']['message']) : '';
