### ISSUE TITLE
Count energy and bandwidth for transaction

### ISSUE THREAD

**Issue by gfijrb** [iexbase/tron-api#38]
Is possibe to get estimated energy and bandwidth before call transaction on smart contract?

**Comment by serderovsh** [comment]
tron-api does not support smart contacts
https://github.com/iexbase/tron-api/blob/master/src/TransactionBuilder.php#L409

**Comment by gfijrb** [comment]
> tron-api does not support smart contacts
> https://github.com/iexbase/tron-api/blob/master/src/TransactionBuilder.php#L409

maybe some algo exist to write it myself
