### ISSUE TITLE
getTransactionsRelated : 400 Bad Request

### ISSUE THREAD

**Issue by bayuns** [iexbase/tron-api#43]
I tried getTransactionsRelated and got the output:

Client error: `POST https://api.trongrid.io/walletextension/gettransactionstothis` resulted in a `400 Bad Request` response: {"success":false,"error":{"code":400,"status":"Bad Request.","message":"TronGrid does not support /walletextension API." (truncated...)

I also read https://developers.tron.network/docs/new-api-service
There might be a slight improvement in the request url

Thankyou

**Comment by serderovsh** [comment]
Developers have disabled this method.

**Comment by bayuns** [comment]
is there a method to get transactions from address?
