### ISSUE TITLE
Issue with latest version

### ISSUE THREAD

**Issue by aralsoft** [iexbase/tron-api#5]
Upgraded to latest version and started getting this error, was working fine before.

Type:        GuzzleHttp\Exception\ServerException
Message:     Server error: `POST https://api.trongrid.io/wallet/getblockbynum` resulted
in a `504 Gateway Time-out` response:

**Comment by aralsoft** [comment]
php ./composer.phar require iexbase/tron-api
Using version ^1.3 for iexbase/tron-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating iexbase/tron-api (v1.3.4 => v1.3.5): Downloading (100%)         
Writing lock file
Generating autoload files

**Comment by serderovsh** [comment]
```php
$fullNode = new HttpProvider('http://13.125.210.234:8090'); 
```

Use ''http://13.125.210.234:8090"

**Comment by aralsoft** [comment]
ok thanks.
