### ISSUE TITLE
Calling a TRC20 Smart Contracts Function Example.

### ISSUE THREAD

**Issue by BlockChainBobC** [iexbase/tron-api#50]
I am pretty new to blockchain programming but am fairly well versed in php and javascript. If I wanted to call a public function in a deployed smart contract is that possible with this api and could you provide some sample code. 

For example, if I wanted to call the public read-only function "calculateTokensReceived" in the smart contract address below, what might that look like, and does this PHP API support that?

```
var the_contact_address = TSXnUzYWuockj3KspfGAd8hnRhshPm1yyw;

// The javascript clientside tronWeb version of what I want to do would look a bit like this:

fund = await tronWeb.contract().at(the_contact_address );

function clientsidecallto_calculateTokensReceived() {
    var _trxtocovert = 1000;
    var _trx_in_suns_to_convert = BigNumber(_trxneeded * 1e18).toFixed(0);

    fund.calculateTokensReceived(amt).call().then(result => {
     console.log('result',result.toString());
       document.getElementById("tokens_you_will_get" ).textContent = (result/1e18).toFixed(2); 
   });
```

If you can put me on the right track to start, I will produce a few examples of making calls to smart contracts and parsing the output for the php api project... Thanks!

**Comment by zottirik** [comment]
yes, it is very important to implement trc20 functions.

**Comment by serderovsh** [comment]
While there is no such function in PHP, we’ll add

**Comment by zottirik** [comment]
Is there any easy way to send TRC20 token with this library?

**Comment by serderovsh** [comment]
no

**Comment by yasar-bug** [comment]
hay I use already node js library with laravel shell command..its perfect work...

**Comment by atlaschiew** [comment]
hi i have made up an article about how to send with trc20 token with use of this library, kindly refer to here https://www.btcschools.net/tron/tron_create_trc20_tx.php

Atlas Chiew
btcschools.net

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618
