### ISSUE TITLE
Cannot install with the latest version of Laravel (8.x)

### ISSUE THREAD

**Issue by bruffstar** [iexbase/tron-api#55]
Laravel requires `guzzlehttp/guzzle` `^7.0.1`

To be able to install tron-api, I had to bump the version down to `6.5.x-dev`

Can Guzzle version be bumped to latest without breaking anything?

**Comment by serderovsh** [comment]
done

**Comment by RaminSubZero** [comment]
this error is not fixed already!

**Comment by RaminSubZero** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - sc0vu/web3.php 0.1.4 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for sc0vu/web3.php ^0.1.4 -> satisfiable by sc0vu/web3.php[0.1.4].
    - Installation request for guzzlehttp/guzzle (locked at 7.1.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.1.1].


Installation failed, reverting ./composer.json to its original content.

**Comment by serderovsh** [comment]
this is already a library dependency  web3

**Comment by RaminSubZero** [comment]
can i ask you to help me resolve this problem

**Comment by serderovsh** [comment]
done 3.1
