### ISSUE TITLE
TRC20 Transfer

### ISSUE THREAD

**Issue by yannambhanuteja** [iexbase/tron-api#56]
There is a function sendToken in this package which accepts token id as parameter to initiate a transaction but we can only get only id for trc10 token but how to transfer trc20 token ?

**Comment by atlaschiew** [comment]
hi i have made up an article about how to send with trc20 token with use of this library, kindly refer to here https://www.btcschools.net/tron/tron_create_trc20_tx.php

Atlas Chiew
btcschools.net

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618
