### ISSUE TITLE
how to transfer trc20-usdt token ?

### ISSUE THREAD

**Issue by ijry** [iexbase/tron-api#57]

**Comment by iPhonePKAndroid** [comment]
how to transfer trc20-usdt token ? #57

**Comment by iPhonePKAndroid** [comment]
upupupup

**Comment by aoeng** [comment]
我也想问

**Comment by iPhonePKAndroid** [comment]
我可以搞定，现在已经可以搞定了，但是要付费



---Original---

**Comment by ijry** [comment]
付费多少钱



发自我的iPhone


------------------ Original ------------------

**Comment by iPhonePKAndroid** [comment]
2000





------------------ Original ------------------

**Comment by ijry** [comment]
2000太多了，500来一套？

**Comment by iPhonePKAndroid** [comment]
我也是付费买的…





------------------ Original ------------------

**Comment by ijry** [comment]
本楼层大家团一个



发自我的iPhone


------------------ Original ------------------

**Comment by ijry** [comment]
> 我也是付费买的…
> […](#)
> ------------------ Original ------------------ From: jry <notifications@github.com&gt; Date: Mon,Nov 23,2020 9:27 PM To: iexbase/tron-api <tron-api@noreply.github.com&gt; Cc: 超级问鼎 <im@zaixiakefu.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [iexbase/tron-api] how to transfer trc20-usdt token ? (#57) 2000太多了，500来一套？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

价格还能便宜不？

**Comment by randyortonx** [comment]
可提供技术支持

**Comment by atlaschiew** [comment]
我把方法写在 https://www.btcschools.net/tron/tron_create_trc20_tx.php 了，希望可以解决你的问题。

Atlas Chiew
btcschools.net

**Comment by ijry** [comment]
> 我把方法写在 https://www.btcschools.net/tron/tron_create_trc20_tx.php 了，希望可以解决你的问题。
> 
> Atlas Chiew
> btcschools.net

thks a lot !!!

**Comment by murasys** [comment]
I want to transfer trc20-usdt from one address to another one 
I'm not sure if i have understood the entire process.
Do i have to transfer 1 TRX to that address to activate it?
Can you please explain me the flow?

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618
