### ISSUE TITLE
"Undefined index: balance" in getAccount

### ISSUE THREAD

**Issue by bayuns** [iexbase/tron-api#6]
public function getBalance(string $address = null, bool $fromTron = false): float
    {
        $address = (!is_null($address) ? $address : $this->address);
        $account = $this->getAccount($address);
 
        if(!$account['balance'] || !array_key_exists('balance', $account)) {
            return 0;
        }
 
        return ($fromTron == true ?
            $this->fromTron($account['balance']) :
            $account['balance']);
    }

**"Undefined index: balance"**

Do you know why the error?

**Comment by serderovsh** [comment]
This is because you entered the wrong address.

**Comment by serderovsh** [comment]
```php
$q->getBalance('TRWBqiqoFZysoAeyR1J35ibuyc8EvhUAoY', true); //result: 3.21107

```

**Comment by bayuns** [comment]
thankyou:)
