### ISSUE TITLE
createSendAssetTransaction() assetBalance is not sufficient.

### ISSUE THREAD

**Issue by bayuns** [iexbase/tron-api#7]
createSendAssetTransaction('TV4NbrAoxheTJCTeEDkAMyqCcWXtG48e9g','TBEteZd9whwjm2Jf8ZWBDFT5uHE147oUwo','ComicCon',1)

array:1 [▼
  "Error" => "class org.tron.core.exception.ContractValidateException : assetBalance is not sufficient."
]

Why is not sufficient?

**Comment by serderovsh** [comment]
```php
$q->createSendAssetTransaction('from',
        'to', 'IPFS', 0.0001)
```

Everything is working

**Comment by bayuns** [comment]
Are there any tips or solutions to my problem? because I have tried transferring some tokens like IPFS, ComicCon, MicrosoftToken, etc and the results are still 'is not sufficient'

**Comment by bayuns** [comment]
yes it works. thankyou.
One question,
What is the minimum amount in transfer of token assets?

**Comment by serderovsh** [comment]
> Are there any tips or solutions to my problem? because I have tried transferring some tokens like IPFS, ComicCon, MicrosoftToken, etc and the results are still 'is not sufficient'

In the near future I will update, revise

**Comment by serderovsh** [comment]
```php
$tron->sendToken('to', 'amount int', 'Code');
```
[#L761](https://github.com/iexbase/tron-api/blob/master/src/Tron.php#L761)
