### ISSUE TITLE
isAddress('my_trx_address_hex') this is not working

### ISSUE THREAD

**Issue by Tulasinathreddy** [iexbase/tron-api#71]
its gving ```false``` when i am entering the correct address also why ?

```
require_once __DIR__ . "/vendor/autoload.php";

use TuriBot\Client;

$add = 'base trx address';
$tron = new \IEXBase\TronAPI\Tron();
$hex = $tron->toHex($add);
$balance =  $tron->isAddress($hex);
```
![image](https://user-images.githubusercontent.com/34623886/103523448-de3a5c80-4ea1-11eb-9eb3-8373de71e6be.png)
![image](https://user-images.githubusercontent.com/34623886/103523469-e5616a80-4ea1-11eb-9782-c34a58ef53d9.png)

All other things like create account and send transactions all are working except this one .! why

to Contact me 
Telegram : [@mrebandev](https://t.me/mrbeandev)

**Comment by TranKimHieu** [comment]
yep, condition `(strlen($address) !== self::ADDRESS_SIZE)` alway return false because`$address = Base58Check::decode($address, 0, 0, false);`
I fixed that: 
 ```
       if (strlen($address) !== self::ADDRESS_SIZE) {
            return false;
        }

        $address = Base58Check::decode($address, 0, 0, false);
```

**Comment by miaoxn** [comment]
[https://github.com/iexbase/tron-api/pull/67/commits/712169b27d07c101077d9db5074269137a5299fd](url)

**Comment by Tulasinathreddy** [comment]
I got it

the correct function to check a address is `validateAddress($address);` 

thank you for developing this TRON API package
