### ISSUE TITLE
How can I check my newly created account?

### ISSUE THREAD

**Issue by romal4u** [iexbase/tron-api#77]
Hello there,

I am using an API for creating a new account but I am not aware that how can I check that my account is created in a production environment or not.

**Comment by neverlose-lv** [comment]
It depends which node you use. Shasta - is a Test net. and regular api.trongrid.io - is the production - the Main net.

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/blob/master/examples/account.php
