### ISSUE TITLE
how to transfer trc20-usdt token？

### ISSUE THREAD

**Issue by linyunming998** [iexbase/tron-api#83]
我把方法写在 https://www.btcschools.net/tron/tron_create_trc20_tx.php 了，希望可以解决你的问题。

Atlas Chiew
btcschools.net

_Originally posted by @atlaschiew in https://github.com/iexbase/tron-api/issues/57#issuecomment-756542863_

我查看了代码，new \Protocol\Transaction() 在哪里获取

**Comment by atlaschiew** [comment]
> 我把方法写在 https://www.btcschools.net/tron/tron_create_trc20_tx.php 了，希望可以解决你的问题。
> 
> Atlas Chiew
> btcschools.net
> 
> _Originally posted by @atlaschiew in [#57 (comment)](https://github.com/iexbase/tron-api/issues/57#issuecomment-756542863)_
> 
> 我查看了代码，new \Protocol\Transaction() 在哪里获取

line 13 - 26 哪里include的, 至于如何把proto格式编译成PHP files,可以参考 https://www.btcschools.net/tron/tron_protobuf.php

**Comment by linyunming998** [comment]
不是 \Google\Protobuf ，我用不是 $_POST['generate_way'] == 'Generate Offline'；没有用到 \Google\Protobuf； 我这里运行代码，报 Class 'Protocol\Transaction' not found，我找了在代码里没有，在哪里可以获取到

**Comment by linyunming998** [comment]
$newTx = new \Protocol\Transaction();
            $parsedRaw =  new \Protocol\Transaction\Raw();
            $parsedRaw->mergeFromString(hex2str($mutatedTx['raw_data_hex']));  这里没地方加载函数

**Comment by atlaschiew** [comment]
> $newTx = new \Protocol\Transaction();
> $parsedRaw = new \Protocol\Transaction\Raw();
> $parsedRaw->mergeFromString(hex2str($mutatedTx['raw_data_hex'])); 这里没地方加载函数

没有办法的 :) 你还是需要 https://github.com/atlaschiew/bitcoin-cryptocurrency-tutorial/tree/master/tron/protobuf/core 里的内容.... 至于它们是如何生成，就要参考回刚刚我给你的编译方法或直接 clone下来

**Comment by linyunming998** [comment]
$ /home/btcschools/protoc/bin/protoc --proto_path='/home/btcschools/wallet-cli/src/main/protos' --php_out='/home/btcschools/public_html/tron/protobuf/core/contract' core/contract/*.proto
执行这一步的时候 报 Could not make proto path relative: core/contract/*.proto: No such file or directory

**Comment by atlaschiew** [comment]
> $ /home/btcschools/protoc/bin/protoc --proto_path='/home/btcschools/wallet-cli/src/main/protos' --php_out='/home/btcschools/public_html/tron/protobuf/core/contract' core/contract/_.proto 执行这一步的时候 报 Could not make proto path relative: core/contract/_.proto: No such file or directory

ok 直接把 prorobuf 文件下载来用吧 ,省心

**Comment by linyunming998** [comment]
好的

**Comment by linyunming998** [comment]
$newTx->setRawData($parsedRaw);
        $signature = Support\Secp::sign($mutatedTx['txID'], $main_privacy_key);
        $newTx->setSignature([hex2str( $signature )]);  执行到这一步了，但是 没有提交到链上

**Comment by atlaschiew** [comment]
> $newTx->setRawData($parsedRaw);
> $signature = Support\Secp::sign($mutatedTx['txID'], $main_privacy_key);
> $newTx->setSignature([hex2str( $signature )]); 执行到这一步了，但是 没有提交到链上

对，不直接提交，这只是生成raw tx, 要提交可以到https://www.btcschools.net/tron/tron_broadcast_tx.php 这里提交

**Comment by linyunming998** [comment]
hex2str 和 str2hex 可以给下么，我这里用自己写的，好像和你的对不上

**Comment by linyunming998** [comment]
提交后 会报 Error! Problem found. {"Error":"class com.google.protobuf.InvalidProtocolBufferException : While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length."}

**Comment by atlaschiew** [comment]
> hex2str 和 str2hex 可以给下么，我这里用自己写的，好像和你的对不上

tron_utils.php 里面

https://www.btcschools.net/tron/tron_start_install.php

**Comment by atlaschiew** [comment]
> 提交后 会报 Error! Problem found. {"Error":"class com.google.protobuf.InvalidProtocolBufferException : While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length."}

先这里测试看如何https://www.btcschools.net/tron/tron_create_trc20_tx.php 。怀疑问题在你的代码

**Comment by linyunming998** [comment]
感谢，调试 可以发送了；还有个问题，如果计算发送需要消耗多少 TRX

**Comment by Kwan9** [comment]
> > 我把方法写在 https://www.btcschools.net/tron/tron_create_trc20_tx.php 了，希望可以解决你的问题。
> > Atlas Chiew
> > btcschools.net
> > _Originally posted by @atlaschiew in [#57 (comment)](https://github.com/iexbase/tron-api/issues/57#issuecomment-756542863)_
> > 我查看了代码，new \Protocol\Transaction() 在哪里获取
> 
> line 13 - 26 哪里include的, 至于如何把proto格式编译成PHP files,可以参考 https://www.btcschools.net/tron/tron_protobuf.php

hi 请问你的这个项目支持部署在win吗? 我架设后创建trc20交易签名那里变空白了

**Comment by atlaschiew** [comment]
> 感谢，调试 可以发送了；还有个问题，如何计算发送TRC20需要消耗多少 TRX

请到 https://github.com/atlaschiew/bitcoin-cryptocurrency-tutorial/issues/new 发问吧

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618  added module, contract

**Comment by Hateem76** [comment]
> [06aae71](https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618) added module, contract

Call to undefined method IEXBase\TronAPI\Tron::contract(). How can I update API. I am using Laravel

**Comment by Hateem76** [comment]
> [06aae71](https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618) added module, contract
Can $tron->createAccount() address be used for TRC20 transaction?
"Failed to execute. Error:Smart contract is not exist."
facing this error when $contract->transfer('toAddress','1','fromAddress');
