### ISSUE TITLE
getTransactionsFromAddress and getTransactionsToAddress don't work

### ISSUE THREAD

**Issue by LuisSB44** [iexbase/tron-api#90]
I am new to tron and I am learning with this project and I want to know if there is any other way to list the transactions of an address or to list the last transactions in general since with the two functions it reflects the error "POST https: // api. trongrid.io / walletextension / gettransactionstothis` resulted in a `405 Not Allowed` response: <html> <head> <title> 405 Not Allowed </title> </head> <body> <center> <h1> 405 Not Allowed </h1> </center> <hr> <center> ngin (truncated ...) "

**Comment by LISONGDASHUAIGE** [comment]
use /v1/accounts/youraddress/transactions
