### ISSUE TITLE
TRC20 Token balance

### ISSUE THREAD

**Issue by ermya** [iexbase/tron-api#92]
how to get TRC20 token balance ?

**Comment by LisenH** [comment]
Solved?

**Comment by ermya** [comment]
Thank you for your response
Yes

**Comment by mahdi4187** [comment]
what?

**Comment by onion83** [comment]
@all https://www.btcschools.net/tron/tron_get_balance.php

**Comment by serderovsh** [comment]
Added module https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618

**Comment by hassan2x** [comment]
> Added module [06aae71](https://github.com/iexbase/tron-api/commit/06aae71ff1234edabeeb2ebd463a0220931d1618)

Call to undefined method IEXBase\TronAPI\Tron::contract(). How can I update my API. I am using laravel
