### ISSUE TITLE
Incorrect error handlling in isAddress (tron.php)

### ISSUE THREAD

**Issue by schgabor1** [iexbase/tron-api#93]
Hi,

The isAddress function first decodes the Base58 address to hex and then checks if the hex's length is 34. However, 34 is the length of the Base58 address.
See here

https://github.com/iexbase/tron-api/blob/82537e3e4df67c0bcf997fb8b894c92c287b068a/src/Tron.php#L1187-L1194

I've fixed it by moving the  size check before BAse58 decoding:
```php
    public function isAddress(string $address = null)
    {
        if(strlen($address) !== self::ADDRESS_SIZE)
        return false;

        $address = Base58Check::decode($address, 0, 0, false);
        $utf8 = hex2bin($address);

        ...
```

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api/blob/master/src/Tron.php#L1211  - Thanks, fixed
